### ISSUE TITLE
Trouble with Jest

### ISSUE THREAD

**Issue by chris93007-wq** [words/brill#23]
Hi I'm using this library in my project however it's in breaking my Jest Tests
<img width="846" alt="image" src="https://user-images.githubusercontent.com/63750494/198367302-62f9ee85-0475-4387-9ca1-f1a8dbdf9f79.png">
<img width="840" alt="image" src="https://user-images.githubusercontent.com/63750494/198367364-62049eb2-396f-40e7-8e41-93f40f8a7f6c.png">
 Could you help me figure what babel or jest configs I would need to resolve this issue?

**Comment by chris93007-wq** [comment]
My jest config - 
<img width="1076" alt="image" src="https://user-images.githubusercontent.com/63750494/198370595-68f596d1-8ba5-4ba8-a49e-d0df8823b222.png">

My babel.rc
<img width="607" alt="image" src="https://user-images.githubusercontent.com/63750494/198370662-67644baa-f4ff-43b7-9af3-4d65699f21e2.png">

**Comment by wooorm** [comment]
This project is ESM: an actual ECMAScript module. It must be imported, not required.
Your project is not ESM. See this for more info: https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c

**Comment by chris93007-wq** [comment]
> https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c
@wooorm 
I am importing it
<img width="536" alt="image" src="https://user-images.githubusercontent.com/63750494/198622104-af6f4354-d5fb-4a9a-b2b2-ba4dc96630ec.png">

**Comment by wooorm** [comment]
> I am importing it

Yeah, that looks good. However, there’s a `require` too. And your config shows a lot of CJS stuff.
You need actual ESM. See the Gist for more info. `type: module` in `package.json`, etc...
